### ISSUE TITLE
API Key is always logged after generation

### ISSUE THREAD

**Issue by mircian** [microsoft/indexnow-wordpress-plugin#17]
https://github.com/microsoft/indexnow-wordpress-plugin/blob/master/public/admin/utils/class-indexnow-url-submission-admin-utils.php#L117

This should probably at least have a `WP_DEBUG` check to avoid exposing the API key.

**Comment by rhurling** [comment]
And I think the linked function is also unused. I couldn't find any use of it.  
As far as I can tell the key is generated here with the same problem: https://github.com/microsoft/indexnow-wordpress-plugin/blob/e34f539c604956e8d719bae859fcd9f1dbfea897/public/includes/class-indexnow-url-submission-activator.php#L23-L27

**Comment by pingal** [comment]
@mircian and @rhurling, thanks for pointing it out. We have addressed it in version 1.0.1
