### ISSUE TITLE
Text Domain Issue

### ISSUE THREAD

**Issue by alexclassroom** [microsoft/indexnow-wordpress-plugin#18]
Your plugin slug is **indexnow**, but current Text Domain is set as **indexnow-url-submission**. As the "Requires at least" is at least 4.6, you could remove the Text Domain tag, but you still need to modify the text domain in all your source files. Make sure it is equal to your plugin slug. (see https://developer.wordpress.org/plugins/internationalization/how-to-internationalize-your-plugin/#text-domains)

**Comment by pingal** [comment]
@alexclassroom, thanks for raising the issue. Fixed in version 1.0.1
